"""Build the repository's provenance graph and analyse it with the same graph
instrument used for computational transition graphs (EXP-H, self-application).

Vocabulary follows W3C PROV-DM loosely: entities (hypothesis revisions,
evidence, run artifacts, concepts, research states), activities (experiment
executions). Edge u -> v means "u was derived from / generated by / used v".

Two graphs are produced:
  versioned   hypothesis revisions are separate nodes (H-001@r0, H-001@r1, ...)
  collapsed   every revision of a hypothesis is merged into one node

    python3 -m tools.provenance        # writes research/provenance/*.json
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from substrate import artifacts as A  # noqa: E402
from substrate.graph import Digraph  # noqa: E402
from substrate.ledger import all_evidence, load_json, read_jsonl, run_index  # noqa: E402

OUT = os.path.join(A.ROOT, "research", "provenance")


def build(collapse=False):
    g = Digraph()
    hyps = load_json("hypotheses.json", [])
    exps = load_json("experiments.json", [])
    concepts = load_json("nomenclature.json", [])
    fails = load_json("failures.json", [])
    discs = load_json("discoveries.json", [])
    states = read_jsonl("research_states.jsonl")
    onto = read_jsonl("ontology_history.jsonl")
    evs = all_evidence()
    runs = run_index()

    def hnode(hid, rev):
        return hid if collapse else "{}@r{}".format(hid, rev)

    for c in concepts:
        g.add_node(c["id"], type="concept")
        for p in c.get("parent_concepts", []):
            g.add_edge(c["id"], p)
    for h in hyps:
        revs = h.get("revision_history", [])
        g.add_node(hnode(h["id"], 0), type="hypothesis")
        for i, r in enumerate(revs, start=1):
            node = hnode(h["id"], i)
            g.add_node(node, type="hypothesis")
            if node != hnode(h["id"], i - 1):
                g.add_edge(node, hnode(h["id"], i - 1))
            for e in r.get("evidence", []):
                g.add_edge(node, e)
        for t in h.get("related_terms", []):
            g.add_edge(hnode(h["id"], 0), t)
    for e in exps:
        g.add_node(e["experiment_id"], type="experiment")
        for h in e.get("hypotheses", []):
            g.add_edge(e["experiment_id"], hnode(h, 0))  # the plan used the hypothesis as first stated
        for r in e.get("runs", []):
            g.add_node(r["run_id"], type="run")
            g.add_edge(r["run_id"], e["experiment_id"])
    for ev in evs:
        g.add_node(ev["id"], type="evidence:" + ev["kind"])
        if ev.get("run_id"):
            g.add_edge(ev["id"], ev["run_id"])
        for d in ev.get("derived_from", []):
            g.add_edge(ev["id"], d)
    for f in fails:
        g.add_node(f["id"], type="failure")
        for x in f.get("related_experiments", []) + f.get("evidence", []):
            g.add_edge(f["id"], x)
    for d in discs:
        g.add_node(d["id"], type="discovery")
        for x in d.get("evidence", []):
            g.add_edge(d["id"], x)
    for o in onto:
        g.add_node(o["id"], type="ontology_change")
        for x in o.get("motivated_by", []):
            g.add_edge(o["id"], x)
    for s in states:
        g.add_node(s["id"], type="research_state")
        if s.get("parent"):
            g.add_edge(s["id"], s["parent"])
        for x in s.get("inputs", []):
            g.add_edge(s["id"], x)
    return g


def analyse(g):
    sccs = [c for c in g.scc() if len(c) > 1]
    types = {}
    for v, a in g.nodes.items():
        t = a.get("type", "referenced_only")
        types[t] = types.get(t, 0) + 1
    out = {"degree": g.degree_stats(), "node_types": dict(sorted(types.items())),
           "is_dag": g.is_dag(), "nontrivial_sccs": [sorted(c) for c in sccs]}
    if out["is_dag"]:
        out["longest_lineage_path"] = g.longest_path_length()
    dangling = sorted(v for v, a in g.nodes.items() if "type" not in a)
    out["dangling_references"] = dangling
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    report = {}
    for name, collapse in (("versioned", False), ("collapsed", True)):
        g = build(collapse)
        report[name] = analyse(g)
        if name == "versioned":
            A.dump(os.path.join(OUT, "provenance_graph.json"),
                   {"nodes": g.nodes, "edges": [[u, v] for u, vs in g.adj.items() for v in vs],
                    "edge_semantics": "u -> v : u was derived from / generated by / used v"})
    A.dump(os.path.join(OUT, "analysis.json"), report)
    print(json.dumps({k: {x: v[x] for x in ("is_dag", "degree", "dangling_references")} | {"n_nontrivial_sccs": len(v["nontrivial_sccs"])}
                      for k, v in report.items()}, indent=1))
    return report


if __name__ == "__main__":
    main()
